export const PATH_NAME = {
    LOGIN: "/login",
    DASHBOARD: "/dashboard",
    STUDENT: "/student/all_students",
    INSTRUCTOR: "/instructor/all_instructors",
    ADD_INSTRUCTOR: "/instructor/add_instructor",
    PAYMENT: "/payment",
    COURSE: "/course/all-course",
    ADD_COURSE: "/course/add-course",
    ANALYTIC: "/analytic",
    TOPIC: "/topic/all-topic",
    ADD_TOPIC: "/topic/add-topic",
    SESSION: "/session/all-sessions",
    ADD_SESSION: "/session/add-session",
    SAP_MODULE: "/sap_module/all_sap_modules",
    ADD_SAP_MODULE: "/sap_module/add_sap_module",
    CERTIFICATE: "/certificate/all_certificates",
    ADD_CERTIFICATE: "/certificate/add_certificate",
    TEST: "/test/all_tests",
    ADD_TEST: "/test/add_test",
    QUESTION_IN_TEST: "/question_in_test/all_questions",
    ADD_QUESTION_IN_TEST: "/question_in_test/add_question",
    QUESTION_BANK: "/question_bank/all_questions",
    ADD_QUESTION_BANK: "/question_bank/add_question",
    ACCOUNT_SETTING: "/account_setting",
};
