export const PATH_NAME = {
    LOGIN: "/login",
    DASHBOARD: "/dashboard",
    STUDENT: "/all_students",
    INSTRUCTOR: "/all_instructors",
    ADD_INSTRUCTOR: "/add_instructor",
    FEE: "/fee",
    COURSE: "/course/all-course",
    ADD_COURSE: "/course/add-course",
    ANALYTIC: "/analytic",
    TOPIC: "/topic/all-topic",
    ADD_TOPIC: "/topic/add-topic",
    SESSION: "session/all-sessions",
    ADD_SESSION: "session/add-session",
    SAP_MODULE: "/all_sap_modules",
    ADD_SAP_MODULE: "/add_sap_module",
    CERTIFICATE: "/all_certificates",
    ADD_CERTIFICATE: "/add_certificate",
};
