export const PATH_NAME = {
    LOGIN: "/login",
    DASHBOARD: "/dashboard",
    STUDENT: "/all_students",
    INSTRUCTOR: "/all_instructors",
    ADD_INSTRUCTOR: "/add_instructor",
    FEE: "/fee",
    COURSE: "/course/all-course",
    ADD_COURSE: "/course/add-course",
    ANALYTIC: "/analytic",
    TOPIC: "/topic/all-topic",
    ADD_TOPIC: "/topic/add-topic",
    SESSION: "session/all-sessions",
    ADD_SESSION: "session/add-session",
};
